import { Component } from '@angular/core';

@Component({
  selector: 'app-manage-users',
  templateUrl: './manage-users.component.html',
  styleUrls: ['./manage-users.component.css']
})
export class ManageUsersComponent {
  list = [
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    },
    {
      profilePic: "FYD",
      username: "user",
      email: "user @gmail.com",
      instaId: "user1234",
      phoneNumber: "1234",
      sendNotification: "sent",
      loginAsUser: "user details",
      action: "will be provided soon",
    }
  ]
  on:boolean = false;
  changeStyle()
  {

  }
}
